"""harvester.records.controlled_terms"""

# Controlled terms for Aardvark field: "dct_format_s"
# https://opengeometadata.org/ogm-aardvark/#format
DCT_FORMAT_S_OGM_TERMS = {
    "ArcGRID",
    "CD - ROM",
    "DEM",
    "DVD - ROM",
    "Feature",
    "Class",
    "Geodatabase",
    "GeoJPEG",
    "GeoJSON",
    "GeoPackage",
    "GeoPDF",
    "GeoTIFF",
    "JPEG",
    "JPEG2000",
    "KML",
    "KMZ",
    "LAS",
    "LAZ",
    "Mixed",
    "MrSID",
    "PDF",
    "PNG",
    "Pulsewaves",
    "Raster",
    "Dataset",
    "Shapefile",
    "SQLite",
    "Database",
    "Tabular",
    "Data",
    "TIFF",
}

# https://opengeometadata.org/ogm-aardvark/#resource-type-values-loc
# note: suggested most applicable to scanned maps
GBL_RESOURCETYPE_SM_LOC_TERMS = {
    "Aerial photographs",
    "Aerial views",
    "Aeronautical charts",
    "Armillary spheres",
    "Astronautical charts",
    "Astronomical models",
    "Atlases",
    "Bathymetric maps",
    "Block diagrams",
    "Bottle-charts",
    "Cadastral maps",
    "Cartographic materials",
    "Cartographic materials for people with visual disabilities",
    "Celestial charts",
    "Celestial globes",
    "Census data",
    "Children's atlases",
    "Children's maps",
    "Comparative maps",
    "Composite atlases",
    "Digital elevation models",
    "Digital maps",
    "Early maps",
    "Ephemerides",
    "Ethnographic maps",
    "Fire insurance maps",
    "Flow maps",
    "Gazetteers",
    "Geological cross-sections",
    "Geological maps",
    "Globes",
    "Gores (Maps)",
    "Gravity anomaly maps",
    "Index maps",
    "Linguistic atlases",
    "Loran charts",
    "Manuscript maps",
    "Mappae mundi",
    "Mental maps",
    "Meteorological charts",
    "Military maps",
    "Mine maps",
    "Miniature maps",
    "Nautical charts",
    "Outline maps",
    "Photogrammetric maps",
    "Photomaps",
    "Physical maps",
    "Pictorial maps",
    "Plotting charts",
    "Portolan charts",
    "Quadrangle maps",
    "Relief models",
    "Remote-sensing maps",
    "Road maps",
    "Statistical maps",
    "Stick charts",
    "Strip maps",
    "Thematic maps",
    "Topographic maps",
    "Tourist maps",
    "Upside-down maps",
    "Wall maps",
    "World atlases",
    "World maps",
    "Worm's-eye views",
    "Zoning maps",
}

# https://opengeometadata.org/ogm-aardvark/#resource-type-values-ogm
# note: suggested most applicable to geospatial data
GBL_RESOURCETYPE_SM_OGM_TERMS = {
    "Annotations",
    "Basemaps",
    "LiDAR",
    "Line data",
    "Mesh data",
    "Multi-spectral data",
    "Oblique photographs",
    "Point cloud data	",
    "Point data",
    "Polygon data",
    "Raster data",
    "Satellite imagery",
    "Streetview photographs",
    "Table data",
}

# Controlled terms for Aardvark field: "gbl_resourceType_sm"
# note: controlled terms are allowed from LOC or OGM terms
GBL_RESOURCETYPE_SM_TERMS = GBL_RESOURCETYPE_SM_LOC_TERMS.union(
    GBL_RESOURCETYPE_SM_OGM_TERMS
)
